lumapps/lumapps-extensions-templates

- template-react-ts/.github/pull_request_template.md
- template-react/.github/pull_request_template.md
Add a PR tempalte for the Extension PR.
This template will be used when partner want to deploy a new version of it's extension or when he want update extension details (name/description/ whitelisted customers/...)
> chore(pr): PR template proposal for partner extension

- template-react-ts/.eslintrc.json
- template-react-ts/package.json
> chore(eslint): add eslint configuration

- template-react-ts/src/config.js
- template-react/package.json
- template-react/src/config.js
Update the configuration file to match the query params neede to create and/or update an extension in MP
Plus update deps in packages.json
> feat(config): update config files for extensions

- index.js
- package.json
- template-react-ts/package.json
- updateVersions.js
Make the updateVersion script able to bump lumx version and bump lumx to 0.27.0
> Bump lumx and update script

- template-react-ts/src/config.js
MP-117
Update the config file to add the links / documentation entry
> feat(config): update config file for documentation

- template-react-ts/src/config.js
MP-117
Add oauth to config file
> feat(config): update config file for oauth applications

- template-react-ts/src/config.js
[MP-220](https://lumapps.atlassian.net/browse/MP-220?atlOrigin=eyJpIjoiNDE2MmYxMjcxOGNhNDI0ZWE2ZWVkNjQ5OWJkYWQ0ZDYiLCJwIjoiaiJ9)
Rename provider to partner in config file
**Have to be merge with this [PR](https://github.com/lumapps/lumapps-extensions-playground/pull/41) impacting the playground**
> feat(config): rename provider to partner

- docs/extensions/dependencies.md
- docs/sdk/skd-js.md
MP-264
Add baseUrl in doc for useContext hooks from SDK
Move dynamic import doc from playground
> feat(doc): add doc base url and dynamic imports

- .github/workflows/github-actions-validator.yml
https://lumapps.atlassian.net/browse/MP-314
> chore(github-workflows): add github-actions-validator

- .gitignore
- template-react-ts/.gitignore
- template-react-ts/.prettierignore
- template-react-ts/package.json
- template-react-ts/src/index.content.ts
- template-react-ts/src/index.global_settings.ts
- template-react-ts/src/index.settings.ts
- template-react-ts/src/index.tsx
- template-react-ts/src/index.widget.no_global.ts
- template-react-ts/src/index.widget.ts
- template-react-ts/src/setupTests.ts
- template-react-ts/src/widget/Widget.tsx
- template-react-ts/src/widget/WidgetGlobalSettings.tsx
- template-react-ts/src/widget/WidgetSettings.tsx
- template-react-ts/src/widget/index.ts
- yarn.lock
Update files and add tsconfig needed for the new build system (webpack)
> Add tests and lint

- docs/extensions/prerequisites.md
Change "hardly" to "strongly" and fix other small typos.
See https://lumapps.slack.com/archives/C01SNJXS6BT/p1627912808001200
> Fix typos in the 'Share To & Widget Extensions' section

- docs.old/playground/build.md
- package.json
- template-widget-extension/package.json
- template-widget-extension/src/config.js
MP-267
Almost all changes were already merge on another PR, so this one is nearly empty now.
Keeping it for very few changes i still want to merge.
> feat(template): update packages and use new builder

- index.js
- template-share-extension/.eslintrc.json
- template-share-extension/.github/pull_request_template.md
- template-share-extension/.gitignore
- template-share-extension/.prettierignore
- template-share-extension/.prettierrc.json
- template-share-extension/package.json
- template-share-extension/public/index.html
- template-share-extension/src/config.js
- template-share-extension/src/extension/Share.tsx
- template-share-extension/src/extension/ShareGlobalSettings.tsx
- template-share-extension/src/extension/defaultGlobalSettings.ts
- template-share-extension/src/index.content.ts
- template-share-extension/src/index.global_settings.ts
- template-share-extension/src/index.tsx
- template-share-extension/src/react-app-env.d.ts
- template-share-extension/src/setupTests.ts
- template-share-extension/src/translations/en.json
- template-share-extension/src/translations/fr.json
- template-share-extension/tsconfig.build.json
- template-share-extension/tsconfig.json
> feat(share): add share extension template

- template-share-extension/package.json
- template-share-extension/src/extension/Share.tsx
- template-share-extension/src/index.tsx
- template-widget-extension/src/index.tsx
- template-widget-extension/src/widget/Widget.tsx
[MP-495](https://lumapps.atlassian.net/browse/MP-495?atlOrigin=eyJpIjoiODUxNjU4NzQ2MTVjNDJjNjliNDJlMmIwMzM5NGJlMzciLCJwIjoiaiJ9)
Update props name of Playground component to match playground modifications
Need to update playground with a new version
> feat(playground): update props name playground

- docs/sdk/sdk-js.md
[MP-530](https://lumapps.atlassian.net/browse/MP-530?atlOrigin=eyJpIjoiMjUyMDhhZGU2MWMzNGM1Mzg5ZGU3YzJlZTkxMGFiNDgiLCJwIjoiaiJ9)
Add apiProfile to the SDK documentation
> feat(doc): add api profile to sdk doc

- docs/extensions/deploy-prod.md
Add a doc page to explain how to request a deployment in production
> doc(deploy): add a doc to explain how to request  deployment

- docs/changelog/playground/1.7.x.md
- package.json
- template-empty-extension/package.json
- template-share-extension/package.json
- template-widget-extension/package.json
update version 1.7.0 of the playground
add changelog
> playground version 1 7 0

- docs/changelog/playground/1.9.x.md
- package.json
- template-empty-extension/package.json
- template-share-extension/package.json
- template-widget-extension/package.json
Update playground to version 1.9.0
Update SDK to 1.4.0
Update Shipping server to 1.3.0
> doc(playground): playground version 1 9 0

- docs/changelog/shipping-server/1.3.x.md
- package.json
- template-empty-extension/package.json
- template-share-extension/package.json
- template-widget-extension/package.json
Add version 1.3.1 of the shipping server
> doc(shipping): shipping version 1 3 1

- docs/sdk/sdk-js.md
[MP-669](https://lumapps.atlassian.net/browse/MP-669?atlOrigin=eyJpIjoiMTA2ZjFmOGVhOTdhNGY1N2FiNzhkOTY0N2QyOWRlYzkiLCJwIjoiaiJ9)
Add doc for environment added to useContext hooks
> chore(sdk): environment hooks

- README.md
- docs/extensions/extension-playground.md
> docs(playground): fix documentation on how to kickstart an extension

- docs/changelog/playground/1.12.x.md
- docs/changelog/playground/1.13.x.md
- docs/changelog/sdk/1.7.x.md
- docs/changelog/shipping-server/1.5.x.md
- docs/sdk/sdk-js.md
- package.json
- template-empty-extension/package.json
- template-share-extension/package.json
- template-widget-extension/package.json
Update packages : 
- sdk : 1.7.1
- playground : 1.13.0
- shipping-server : 1.5.0
Update doc : 
- Add accountType to current User
- Add useFeatureEnabled hooks
Update changelog
> chore(template): update packages and doc

- docs/changelog/customizations-api/1.0.X.md
- docs/customizations-api/javascript/capabilities.md
New Customisations API version deployed, this PR updates the documentation associated to it.
> chore(customisations): added placements for nav and sub nav

- docs/changelog/playground/1.14.x.md
- docs/changelog/sdk/1.8.x.md
- docs/sdk/sdk-js.md
- template-empty-extension/package.json
- template-share-extension/package.json
- template-widget-extension/package.json
Update version : 
- SDK : 1.8.0
- Playground : 1.14.0
Add doc for isDesignerMode
> chore(template): update sdk playground version and doc

- docs/customizations-api/javascript/use-cases.md
Update external service documentation
> chore(capi): update external service call

- docs/changelog/playground/1.17.x.md
- docs/changelog/shipping-server/1.7.x.md
- package.json
- template-empty-extension/package.json
- template-search-extension/package.json
- template-share-extension/package.json
- template-widget-extension/package.json
Update shipping-server to 1.7.0
Update playground to 1.17.0
Update changelogs
> chore(template): update packages

- docs/tools/index.md
> docs(hooks): add documentation for useWidgetEmptyState hook

- .github/workflows/release-note.yml
Also use a frozen version to prevent breaking
> chore(release): update the changelog generate

- docs/changelog/sdk/1.12.x.md
- docs/changelog/sdk/1.13.x.md
- docs/changelog/sdk/1.14.x.md
- docs/changelog/sdk/1.15.x.md
- package.json
- template-backend-extension/package.json
- template-empty-extension/package.json
- template-search-extension/package.json
- template-share-extension/package.json
- template-widget-extension/package.json
[MP-1236](https://lumapps.atlassian.net/browse/MP-1236?atlOrigin=eyJpIjoiZWJjZTk1YzE1MjQ2NDg5MThkMmY1MTEwMzc5NmZkZTEiLCJwIjoiaiJ9)
Update SDK version
Update changelog
> feat(sdk): update sdk version 1.15.0

- template-backend-extension/package.json
- template-backend-extension/src/config.js
- template-empty-extension/package.json
- template-empty-extension/src/config.js
- template-search-extension/package.json
- template-widget-extension/package.json
- template-widget-extension/src/config.js
> fix(config): edit documentation link

- docs/changelog/sdk/1.15.x.md
- docs/changelog/sdk/1.16.x.md
- docs/changelog/sdk/1.17.x.md
- docs/changelog/sdk/1.18.x.md
- docs/changelog/sdk/1.19.x.md
- docs/changelog/sdk/1.20.x.md
- docs/changelog/sdk/1.21.x.md
- docs/changelog/sdk/1.22.x.md
- docs/changelog/sdk/1.23.x.md
- docs/changelog/sdk/1.24.x.md
- docs/changelog/sdk/1.25.x.md
- docs/changelog/sdk/1.26.x.md
- docs/changelog/sdk/1.27.x.md
- docs/changelog/sdk/1.28.x.md
- docs/changelog/sdk/1.29.x.md
> docs(sdk): add changelogs from 1.15.0 to 1.29.0
